/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 46
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_PIPE_PIPE = 4,
  anon_sym_AMP_AMP = 5,
  anon_sym_PIPE = 6,
  anon_sym_CARET = 7,
  anon_sym_AMP = 8,
  anon_sym_EQ_EQ = 9,
  anon_sym_BANG_EQ = 10,
  anon_sym_GT = 11,
  anon_sym_LT = 12,
  anon_sym_GT_EQ = 13,
  anon_sym_LT_EQ = 14,
  anon_sym_LT_LT = 15,
  anon_sym_GT_GT = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_PERCENT = 21,
  anon_sym_as = 22,
  anon_sym_bitcast = 23,
  anon_sym_DOT = 24,
  anon_sym_BANG = 25,
  anon_sym_TILDE = 26,
  sym_name = 27,
  aux_sym_number_token1 = 28,
  aux_sym_number_token2 = 29,
  aux_sym_number_token3 = 30,
  aux_sym_number_token4 = 31,
  sym_char = 32,
  sym_string = 33,
  anon_sym_true = 34,
  anon_sym_false = 35,
  sym_source_file = 36,
  sym_field = 37,
  sym_expr = 38,
  sym_literal_expr = 39,
  sym_binary_expr = 40,
  sym_unary_expr = 41,
  sym_number = 42,
  sym_bool = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_as] = "as",
  [anon_sym_bitcast] = "bitcast",
  [anon_sym_DOT] = ".",
  [anon_sym_BANG] = "!",
  [anon_sym_TILDE] = "~",
  [sym_name] = "name",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [sym_char] = "char",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_field] = "field",
  [sym_expr] = "expr",
  [sym_literal_expr] = "literal_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_number] = "number",
  [sym_bool] = "bool",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_bitcast] = anon_sym_bitcast,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [sym_name] = sym_name,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_field] = sym_field,
  [sym_expr] = sym_expr,
  [sym_literal_expr] = sym_literal_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_number] = sym_number,
  [sym_bool] = sym_bool,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bitcast] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '!', 57,
        '"', 3,
        '%', 52,
        '&', 38,
        '\'', 7,
        '*', 50,
        '+', 47,
        '-', 49,
        '.', 55,
        '/', 51,
        '0', 61,
        ':', 30,
        ';', 29,
        '<', 42,
        '=', 32,
        '>', 41,
        '^', 36,
        'a', 16,
        'b', 13,
        'f', 8,
        't', 15,
        '|', 35,
        '~', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 6,
        '%', 52,
        '&', 38,
        '*', 50,
        '+', 47,
        '-', 48,
        '.', 55,
        '/', 51,
        ':', 30,
        ';', 29,
        '<', 42,
        '=', 32,
        '>', 41,
        '^', 36,
        'a', 16,
        'b', 13,
        '|', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 56,
        '"', 3,
        '&', 37,
        '\'', 7,
        '*', 50,
        '-', 49,
        '0', 61,
        ':', 30,
        ';', 29,
        '=', 31,
        'f', 8,
        't', 15,
        '~', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead == '\\') ADVANCE(27);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(66);
      END_STATE();
    case 6:
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 22:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(65);
      END_STATE();
    case 23:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(64);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(33);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(34);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(43);
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == '=') ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '0') ADVANCE(61);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_bitcast);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(40);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == '.') ADVANCE(25);
      if (lookahead == 'b') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(24);
      if (lookahead == 'x') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == '.') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '\'') ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_bitcast] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym_field] = STATE(43),
    [sym_name] = ACTIONS(3),
  },
  [STATE(2)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(3)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(4)] = {
    [anon_sym_SEMI] = ACTIONS(37),
    [anon_sym_COLON] = ACTIONS(37),
    [anon_sym_EQ] = ACTIONS(39),
    [anon_sym_PIPE_PIPE] = ACTIONS(37),
    [anon_sym_AMP_AMP] = ACTIONS(37),
    [anon_sym_PIPE] = ACTIONS(39),
    [anon_sym_CARET] = ACTIONS(37),
    [anon_sym_AMP] = ACTIONS(39),
    [anon_sym_EQ_EQ] = ACTIONS(37),
    [anon_sym_BANG_EQ] = ACTIONS(37),
    [anon_sym_GT] = ACTIONS(39),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_GT_EQ] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(37),
    [anon_sym_LT_LT] = ACTIONS(37),
    [anon_sym_GT_GT] = ACTIONS(37),
    [anon_sym_PLUS] = ACTIONS(37),
    [anon_sym_DASH] = ACTIONS(37),
    [anon_sym_STAR] = ACTIONS(37),
    [anon_sym_SLASH] = ACTIONS(37),
    [anon_sym_PERCENT] = ACTIONS(37),
    [anon_sym_as] = ACTIONS(37),
    [anon_sym_bitcast] = ACTIONS(37),
    [anon_sym_DOT] = ACTIONS(37),
  },
  [STATE(5)] = {
    [anon_sym_SEMI] = ACTIONS(41),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_EQ] = ACTIONS(43),
    [anon_sym_PIPE_PIPE] = ACTIONS(41),
    [anon_sym_AMP_AMP] = ACTIONS(41),
    [anon_sym_PIPE] = ACTIONS(43),
    [anon_sym_CARET] = ACTIONS(41),
    [anon_sym_AMP] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(41),
    [anon_sym_BANG_EQ] = ACTIONS(41),
    [anon_sym_GT] = ACTIONS(43),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(41),
    [anon_sym_LT_LT] = ACTIONS(41),
    [anon_sym_GT_GT] = ACTIONS(41),
    [anon_sym_PLUS] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(41),
    [anon_sym_STAR] = ACTIONS(41),
    [anon_sym_SLASH] = ACTIONS(41),
    [anon_sym_PERCENT] = ACTIONS(41),
    [anon_sym_as] = ACTIONS(41),
    [anon_sym_bitcast] = ACTIONS(41),
    [anon_sym_DOT] = ACTIONS(41),
  },
  [STATE(6)] = {
    [anon_sym_SEMI] = ACTIONS(45),
    [anon_sym_COLON] = ACTIONS(45),
    [anon_sym_EQ] = ACTIONS(47),
    [anon_sym_PIPE_PIPE] = ACTIONS(45),
    [anon_sym_AMP_AMP] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [anon_sym_CARET] = ACTIONS(45),
    [anon_sym_AMP] = ACTIONS(47),
    [anon_sym_EQ_EQ] = ACTIONS(45),
    [anon_sym_BANG_EQ] = ACTIONS(45),
    [anon_sym_GT] = ACTIONS(47),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_GT_EQ] = ACTIONS(45),
    [anon_sym_LT_EQ] = ACTIONS(45),
    [anon_sym_LT_LT] = ACTIONS(45),
    [anon_sym_GT_GT] = ACTIONS(45),
    [anon_sym_PLUS] = ACTIONS(45),
    [anon_sym_DASH] = ACTIONS(45),
    [anon_sym_STAR] = ACTIONS(45),
    [anon_sym_SLASH] = ACTIONS(45),
    [anon_sym_PERCENT] = ACTIONS(45),
    [anon_sym_as] = ACTIONS(45),
    [anon_sym_bitcast] = ACTIONS(45),
    [anon_sym_DOT] = ACTIONS(45),
  },
  [STATE(7)] = {
    [anon_sym_SEMI] = ACTIONS(49),
    [anon_sym_COLON] = ACTIONS(49),
    [anon_sym_EQ] = ACTIONS(51),
    [anon_sym_PIPE_PIPE] = ACTIONS(49),
    [anon_sym_AMP_AMP] = ACTIONS(49),
    [anon_sym_PIPE] = ACTIONS(51),
    [anon_sym_CARET] = ACTIONS(49),
    [anon_sym_AMP] = ACTIONS(51),
    [anon_sym_EQ_EQ] = ACTIONS(49),
    [anon_sym_BANG_EQ] = ACTIONS(49),
    [anon_sym_GT] = ACTIONS(51),
    [anon_sym_LT] = ACTIONS(51),
    [anon_sym_GT_EQ] = ACTIONS(49),
    [anon_sym_LT_EQ] = ACTIONS(49),
    [anon_sym_LT_LT] = ACTIONS(49),
    [anon_sym_GT_GT] = ACTIONS(49),
    [anon_sym_PLUS] = ACTIONS(49),
    [anon_sym_DASH] = ACTIONS(49),
    [anon_sym_STAR] = ACTIONS(49),
    [anon_sym_SLASH] = ACTIONS(49),
    [anon_sym_PERCENT] = ACTIONS(49),
    [anon_sym_as] = ACTIONS(49),
    [anon_sym_bitcast] = ACTIONS(49),
    [anon_sym_DOT] = ACTIONS(49),
  },
  [STATE(8)] = {
    [anon_sym_SEMI] = ACTIONS(53),
    [anon_sym_COLON] = ACTIONS(55),
    [anon_sym_EQ] = ACTIONS(57),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(9)] = {
    [anon_sym_SEMI] = ACTIONS(59),
    [anon_sym_COLON] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(61),
    [anon_sym_PIPE_PIPE] = ACTIONS(59),
    [anon_sym_AMP_AMP] = ACTIONS(59),
    [anon_sym_PIPE] = ACTIONS(61),
    [anon_sym_CARET] = ACTIONS(59),
    [anon_sym_AMP] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(59),
    [anon_sym_BANG_EQ] = ACTIONS(59),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_LT_LT] = ACTIONS(59),
    [anon_sym_GT_GT] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_PERCENT] = ACTIONS(59),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(10)] = {
    [anon_sym_SEMI] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(11)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(12)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(13)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(14)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(15)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(16)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(17)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_LT_LT] = ACTIONS(5),
    [anon_sym_GT_GT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(18)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_LT_LT] = ACTIONS(5),
    [anon_sym_GT_GT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(19)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_LT_LT] = ACTIONS(5),
    [anon_sym_GT_GT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(20)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_LT_LT] = ACTIONS(5),
    [anon_sym_GT_GT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [anon_sym_bitcast] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(21)] = {
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(5),
    [anon_sym_AMP_AMP] = ACTIONS(5),
    [anon_sym_PIPE] = ACTIONS(7),
    [anon_sym_CARET] = ACTIONS(5),
    [anon_sym_AMP] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(5),
    [anon_sym_BANG_EQ] = ACTIONS(5),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(5),
    [anon_sym_LT_LT] = ACTIONS(5),
    [anon_sym_GT_GT] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(5),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(5),
    [anon_sym_PERCENT] = ACTIONS(5),
    [anon_sym_as] = ACTIONS(5),
    [anon_sym_bitcast] = ACTIONS(5),
    [anon_sym_DOT] = ACTIONS(5),
  },
  [STATE(22)] = {
    [anon_sym_SEMI] = ACTIONS(65),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
  [STATE(23)] = {
    [anon_sym_SEMI] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(31),
    [anon_sym_AMP_AMP] = ACTIONS(33),
    [anon_sym_PIPE] = ACTIONS(35),
    [anon_sym_CARET] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_EQ_EQ] = ACTIONS(13),
    [anon_sym_BANG_EQ] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(15),
    [anon_sym_GT_EQ] = ACTIONS(17),
    [anon_sym_LT_EQ] = ACTIONS(17),
    [anon_sym_LT_LT] = ACTIONS(19),
    [anon_sym_GT_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(21),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(23),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_as] = ACTIONS(25),
    [anon_sym_bitcast] = ACTIONS(25),
    [anon_sym_DOT] = ACTIONS(27),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(67), 1,
      anon_sym_SEMI,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(8), 1,
      sym_expr,
    ACTIONS(69), 2,
      anon_sym_COLON,
      anon_sym_EQ,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [45] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(15), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [83] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(21), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [121] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(19), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [159] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(20), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [197] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(23), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [235] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(3), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [273] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(22), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [311] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(9), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [349] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(10), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [387] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(11), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [425] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(12), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [463] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(2), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [501] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(13), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [539] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(14), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [577] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(17), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [615] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(16), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [653] = 9,
    ACTIONS(73), 1,
      anon_sym_DASH,
    ACTIONS(77), 1,
      aux_sym_number_token2,
    STATE(18), 1,
      sym_expr,
    ACTIONS(79), 2,
      sym_char,
      sym_string,
    ACTIONS(81), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_number,
      sym_bool,
    ACTIONS(75), 3,
      aux_sym_number_token1,
      aux_sym_number_token3,
      aux_sym_number_token4,
    STATE(6), 3,
      sym_literal_expr,
      sym_binary_expr,
      sym_unary_expr,
    ACTIONS(71), 4,
      anon_sym_AMP,
      anon_sym_STAR,
      anon_sym_BANG,
      anon_sym_TILDE,
  [691] = 1,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
  [695] = 1,
    ACTIONS(85), 1,
      anon_sym_SEMI,
  [699] = 1,
    ACTIONS(87), 1,
      anon_sym_COLON,
  [703] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 45,
  [SMALL_STATE(26)] = 83,
  [SMALL_STATE(27)] = 121,
  [SMALL_STATE(28)] = 159,
  [SMALL_STATE(29)] = 197,
  [SMALL_STATE(30)] = 235,
  [SMALL_STATE(31)] = 273,
  [SMALL_STATE(32)] = 311,
  [SMALL_STATE(33)] = 349,
  [SMALL_STATE(34)] = 387,
  [SMALL_STATE(35)] = 425,
  [SMALL_STATE(36)] = 463,
  [SMALL_STATE(37)] = 501,
  [SMALL_STATE(38)] = 539,
  [SMALL_STATE(39)] = 577,
  [SMALL_STATE(40)] = 615,
  [SMALL_STATE(41)] = 653,
  [SMALL_STATE(42)] = 691,
  [SMALL_STATE(43)] = 695,
  [SMALL_STATE(44)] = 699,
  [SMALL_STATE(45)] = 703,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_expr, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_expr, 1, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expr, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stra(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "stra",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
