/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 20
#define SYMBOL_COUNT 54
#define ALIAS_COUNT 0
#define TOKEN_COUNT 45
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COLON = 2,
  anon_sym_EQ = 3,
  anon_sym_PIPE_PIPE = 4,
  anon_sym_AMP_AMP = 5,
  anon_sym_PIPE = 6,
  anon_sym_CARET = 7,
  anon_sym_AMP = 8,
  anon_sym_EQ_EQ = 9,
  anon_sym_BANG_EQ = 10,
  anon_sym_GT = 11,
  anon_sym_LT = 12,
  anon_sym_GT_EQ = 13,
  anon_sym_LT_EQ = 14,
  anon_sym_LT_LT = 15,
  anon_sym_GT_GT = 16,
  anon_sym_PLUS = 17,
  anon_sym_DASH = 18,
  anon_sym_STAR = 19,
  anon_sym_SLASH = 20,
  anon_sym_PERCENT = 21,
  anon_sym_as = 22,
  anon_sym_bitcast = 23,
  anon_sym_DOT = 24,
  anon_sym_BANG = 25,
  anon_sym_TILDE = 26,
  anon_sym_void = 27,
  anon_sym_bool = 28,
  aux_sym_primitive_type_token1 = 29,
  anon_sym_usize = 30,
  anon_sym_isize = 31,
  anon_sym_f16 = 32,
  anon_sym_f32 = 33,
  anon_sym_f64 = 34,
  anon_sym_f128 = 35,
  sym_name = 36,
  aux_sym_number_token1 = 37,
  aux_sym_number_token2 = 38,
  aux_sym_number_token3 = 39,
  aux_sym_number_token4 = 40,
  sym_char = 41,
  sym_string = 42,
  anon_sym_true = 43,
  anon_sym_false = 44,
  sym_source_file = 45,
  sym_field = 46,
  sym_expr = 47,
  sym_literal_expr = 48,
  sym_binary_expr = 49,
  sym_unary_expr = 50,
  sym_primitive_type = 51,
  sym_number = 52,
  sym_bool = 53,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COLON] = ":",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE] = "|",
  [anon_sym_CARET] = "^",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_as] = "as",
  [anon_sym_bitcast] = "bitcast",
  [anon_sym_DOT] = ".",
  [anon_sym_BANG] = "!",
  [anon_sym_TILDE] = "~",
  [anon_sym_void] = "void",
  [anon_sym_bool] = "bool",
  [aux_sym_primitive_type_token1] = "primitive_type_token1",
  [anon_sym_usize] = "usize",
  [anon_sym_isize] = "isize",
  [anon_sym_f16] = "f16",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_f128] = "f128",
  [sym_name] = "name",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_number_token3] = "number_token3",
  [aux_sym_number_token4] = "number_token4",
  [sym_char] = "char",
  [sym_string] = "string",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_field] = "field",
  [sym_expr] = "expr",
  [sym_literal_expr] = "literal_expr",
  [sym_binary_expr] = "binary_expr",
  [sym_unary_expr] = "unary_expr",
  [sym_primitive_type] = "primitive_type",
  [sym_number] = "number",
  [sym_bool] = "bool",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_bitcast] = anon_sym_bitcast,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_void] = anon_sym_void,
  [anon_sym_bool] = anon_sym_bool,
  [aux_sym_primitive_type_token1] = aux_sym_primitive_type_token1,
  [anon_sym_usize] = anon_sym_usize,
  [anon_sym_isize] = anon_sym_isize,
  [anon_sym_f16] = anon_sym_f16,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_f128] = anon_sym_f128,
  [sym_name] = sym_name,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_number_token3] = aux_sym_number_token3,
  [aux_sym_number_token4] = aux_sym_number_token4,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_field] = sym_field,
  [sym_expr] = sym_expr,
  [sym_literal_expr] = sym_literal_expr,
  [sym_binary_expr] = sym_binary_expr,
  [sym_unary_expr] = sym_unary_expr,
  [sym_primitive_type] = sym_primitive_type,
  [sym_number] = sym_number,
  [sym_bool] = sym_bool,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bitcast] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_void] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_primitive_type_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_usize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_isize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f128] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token4] = {
    .visible = false,
    .named = false,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_type] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_default = 1,
  field_name = 2,
  field_type = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_default] = "default",
  [field_name] = "name",
  [field_type] = "type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_type, 2},
  [3] =
    {field_default, 3},
    {field_name, 0},
  [5] =
    {field_default, 4},
    {field_name, 0},
    {field_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(47);
      ADVANCE_MAP(
        '!', 76,
        '"', 3,
        '%', 71,
        '&', 57,
        '\'', 12,
        '*', 69,
        '+', 66,
        '-', 68,
        '.', 74,
        '/', 70,
        '0', 89,
        ':', 49,
        ';', 48,
        '<', 61,
        '=', 51,
        '>', 60,
        '^', 55,
        'a', 31,
        'b', 21,
        'f', 6,
        'i', 32,
        't', 30,
        'u', 35,
        'v', 29,
        '|', 54,
        '~', 77,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 75,
        '"', 3,
        '&', 56,
        '\'', 12,
        '*', 69,
        '-', 68,
        '0', 89,
        ':', 49,
        ';', 48,
        '=', 50,
        'b', 27,
        'f', 6,
        'i', 32,
        't', 30,
        'u', 35,
        'v', 29,
        '~', 77,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 11,
        '%', 71,
        '&', 57,
        '*', 69,
        '+', 66,
        '-', 67,
        '.', 74,
        '/', 70,
        ':', 49,
        ';', 48,
        '<', 61,
        '=', 51,
        '>', 60,
        '^', 55,
        'a', 31,
        'b', 20,
        '|', 54,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(94);
      END_STATE();
    case 6:
      if (lookahead == '1') ADVANCE(7);
      if (lookahead == '3') ADVANCE(8);
      if (lookahead == '6') ADVANCE(9);
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 7:
      if (lookahead == '2') ADVANCE(10);
      if (lookahead == '6') ADVANCE(83);
      END_STATE();
    case 8:
      if (lookahead == '2') ADVANCE(84);
      END_STATE();
    case 9:
      if (lookahead == '4') ADVANCE(85);
      END_STATE();
    case 10:
      if (lookahead == '8') ADVANCE(86);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 12:
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(78);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(36);
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(38);
      END_STATE();
    case 31:
      if (lookahead == 's') ADVANCE(72);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 38:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 39:
      if (lookahead == 'z') ADVANCE(18);
      END_STATE();
    case 40:
      if (lookahead == 'z') ADVANCE(19);
      END_STATE();
    case 41:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(93);
      END_STATE();
    case 42:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(92);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      END_STATE();
    case 46:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(58);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(52);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(53);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead == '>') ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(64);
      if (lookahead == '=') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '0') ADVANCE(89);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_bitcast);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(59);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_void);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_primitive_type_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_usize);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_isize);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_f16);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_f128);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == 'b') ADVANCE(41);
      if (lookahead == 'o') ADVANCE(43);
      if (lookahead == 'x') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (lookahead == '.') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_number_token3);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_number_token4);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_char);
      if (lookahead == '\'') ADVANCE(94);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 42},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_bitcast] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_void] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [aux_sym_primitive_type_token1] = ACTIONS(1),
    [anon_sym_usize] = ACTIONS(1),
    [anon_sym_isize] = ACTIONS(1),
    [anon_sym_f16] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_f128] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_number_token3] = ACTIONS(1),
    [aux_sym_number_token4] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(43),
    [sym_field] = STATE(46),
    [sym_name] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_expr] = STATE(23),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_SEMI] = ACTIONS(5),
    [anon_sym_COLON] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(3)] = {
    [sym_expr] = STATE(30),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(4)] = {
    [sym_expr] = STATE(40),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(5)] = {
    [sym_expr] = STATE(41),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(6)] = {
    [sym_expr] = STATE(26),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(7)] = {
    [sym_expr] = STATE(42),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(8)] = {
    [sym_expr] = STATE(21),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(9)] = {
    [sym_expr] = STATE(29),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(10)] = {
    [sym_expr] = STATE(31),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(11)] = {
    [sym_expr] = STATE(32),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(12)] = {
    [sym_expr] = STATE(33),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(13)] = {
    [sym_expr] = STATE(20),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(14)] = {
    [sym_expr] = STATE(35),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(15)] = {
    [sym_expr] = STATE(36),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(16)] = {
    [sym_expr] = STATE(37),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(17)] = {
    [sym_expr] = STATE(38),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(18)] = {
    [sym_expr] = STATE(39),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
  [STATE(19)] = {
    [sym_expr] = STATE(34),
    [sym_literal_expr] = STATE(24),
    [sym_binary_expr] = STATE(24),
    [sym_unary_expr] = STATE(24),
    [sym_primitive_type] = STATE(24),
    [sym_number] = STATE(27),
    [sym_bool] = STATE(27),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_STAR] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(9),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_void] = ACTIONS(13),
    [anon_sym_bool] = ACTIONS(13),
    [aux_sym_primitive_type_token1] = ACTIONS(13),
    [anon_sym_usize] = ACTIONS(13),
    [anon_sym_isize] = ACTIONS(13),
    [anon_sym_f16] = ACTIONS(13),
    [anon_sym_f32] = ACTIONS(13),
    [anon_sym_f64] = ACTIONS(13),
    [anon_sym_f128] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
    [aux_sym_number_token3] = ACTIONS(15),
    [aux_sym_number_token4] = ACTIONS(15),
    [sym_char] = ACTIONS(19),
    [sym_string] = ACTIONS(19),
    [anon_sym_true] = ACTIONS(21),
    [anon_sym_false] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(25), 3,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(23), 7,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
  [43] = 16,
    ACTIONS(23), 1,
      anon_sym_COLON,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_SEMI,
    ACTIONS(43), 1,
      anon_sym_EQ,
    ACTIONS(45), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(47), 1,
      anon_sym_AMP_AMP,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [100] = 2,
    ACTIONS(59), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(57), 19,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
      anon_sym_DOT,
  [129] = 16,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(45), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(47), 1,
      anon_sym_AMP_AMP,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(61), 1,
      anon_sym_SEMI,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      anon_sym_EQ,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [186] = 2,
    ACTIONS(69), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(67), 19,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
      anon_sym_DOT,
  [215] = 2,
    ACTIONS(73), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(71), 19,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
      anon_sym_DOT,
  [244] = 4,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(77), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(75), 16,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [277] = 2,
    ACTIONS(81), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(79), 19,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
      anon_sym_DOT,
  [306] = 2,
    ACTIONS(85), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(83), 19,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
      anon_sym_DOT,
  [335] = 14,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(47), 1,
      anon_sym_AMP_AMP,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(23), 3,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [388] = 13,
    ACTIONS(25), 1,
      anon_sym_EQ,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(23), 4,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [439] = 12,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(25), 2,
      anon_sym_EQ,
      anon_sym_PIPE,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(23), 4,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
  [488] = 11,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(25), 2,
      anon_sym_EQ,
      anon_sym_PIPE,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(23), 5,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
  [535] = 10,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(25), 3,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(23), 5,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
  [580] = 2,
    ACTIONS(25), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 19,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
      anon_sym_DOT,
  [609] = 7,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(25), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 9,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
  [648] = 6,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(25), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 11,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
  [685] = 5,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(25), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 13,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
  [720] = 4,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(25), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 16,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [753] = 3,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(25), 5,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(23), 18,
      anon_sym_SEMI,
      anon_sym_COLON,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_CARET,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_as,
      anon_sym_bitcast,
  [784] = 15,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(43), 1,
      anon_sym_EQ,
    ACTIONS(45), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(47), 1,
      anon_sym_AMP_AMP,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(23), 2,
      anon_sym_SEMI,
      anon_sym_COLON,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [839] = 15,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(43), 1,
      anon_sym_EQ,
    ACTIONS(45), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(47), 1,
      anon_sym_AMP_AMP,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [893] = 15,
    ACTIONS(39), 1,
      anon_sym_DOT,
    ACTIONS(41), 1,
      anon_sym_SEMI,
    ACTIONS(43), 1,
      anon_sym_EQ,
    ACTIONS(45), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(47), 1,
      anon_sym_AMP_AMP,
    ACTIONS(49), 1,
      anon_sym_PIPE,
    ACTIONS(51), 1,
      anon_sym_CARET,
    ACTIONS(53), 1,
      anon_sym_AMP,
    ACTIONS(27), 2,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(29), 2,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
    ACTIONS(31), 2,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
    ACTIONS(33), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 2,
      anon_sym_as,
      anon_sym_bitcast,
    ACTIONS(55), 2,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
    ACTIONS(35), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
  [947] = 1,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
  [951] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [955] = 1,
    ACTIONS(93), 1,
      anon_sym_COLON,
  [959] = 1,
    ACTIONS(95), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(20)] = 0,
  [SMALL_STATE(21)] = 43,
  [SMALL_STATE(22)] = 100,
  [SMALL_STATE(23)] = 129,
  [SMALL_STATE(24)] = 186,
  [SMALL_STATE(25)] = 215,
  [SMALL_STATE(26)] = 244,
  [SMALL_STATE(27)] = 277,
  [SMALL_STATE(28)] = 306,
  [SMALL_STATE(29)] = 335,
  [SMALL_STATE(30)] = 388,
  [SMALL_STATE(31)] = 439,
  [SMALL_STATE(32)] = 488,
  [SMALL_STATE(33)] = 535,
  [SMALL_STATE(34)] = 580,
  [SMALL_STATE(35)] = 609,
  [SMALL_STATE(36)] = 648,
  [SMALL_STATE(37)] = 685,
  [SMALL_STATE(38)] = 720,
  [SMALL_STATE(39)] = 753,
  [SMALL_STATE(40)] = 784,
  [SMALL_STATE(41)] = 839,
  [SMALL_STATE(42)] = 893,
  [SMALL_STATE(43)] = 947,
  [SMALL_STATE(44)] = 951,
  [SMALL_STATE(45)] = 955,
  [SMALL_STATE(46)] = 959,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 2, 0, 1),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expr, 3, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 5, 0, 4),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expr, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expr, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_expr, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_expr, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_type, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 4, 0, 3),
  [89] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stra(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "stra",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
